theme = "solarized-light"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
format = "{utilization}% {frequency}GHz"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "94:DB:56:D5:22:A6"
label = " WH-1000XM4"
hide_disconnected = true

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
on_collapsed_click = "quodlibet"
on_click = "quodlibet"
dynamic_width = true
marquee = true
marquee_speed = 1

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time} {power}W"
device = "DisplayDevice"

[[block]]
block = "time"
interval = 1
format = "%a %F %T"
locale = "ja_JP"
